# Generated by Django 3.1.3 on 2021-01-18 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=256, null=True)),
                ('location', models.CharField(choices=[('kothrud', 'Kothrud'), ('swargate', 'Swargate'), ('wakad', 'Wakad'), ('aundh', 'Aundh'), ('katraj', 'Katraj')], default='kothrud', max_length=20)),
                ('number', models.BigIntegerField(null=True)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
