# Generated by Django 3.1.3 on 2021-02-02 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0010_auto_20210202_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='timeslot',
            field=models.CharField(choices=[('09:00\xa0–\xa010:00', '09:00\xa0–\xa010:00'), ('10:00\xa0–\xa011:00', '10:00\xa0–\xa011:00'), ('11:00\xa0–\xa012:00', '11:00\xa0–\xa012:00'), ('12:00\xa0–\xa013:00', '12:00\xa0–\xa013:00'), ('13:00\xa0–\xa014:00', '13:00\xa0–\xa014:00'), ('14:00\xa0–\xa015:00', '14:00\xa0–\xa015:00'), ('15:00\xa0–\xa016:00', '15:00\xa0–\xa016:00'), ('16:00\xa0–\xa017:00', '16:00\xa0–\xa017:00'), ('17:00\xa0–\xa018:00', '17:00\xa0–\xa018:00')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
