# Generated by Django 3.1.3 on 2021-02-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_20210202_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.BooleanField(choices=[(False, 'Pending'), (True, 'Closed')], default=False),
        ),
    ]
