# Generated by Django 3.1.3 on 2021-02-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_appointment_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Closed'), (3, 'Cancle')], default=1),
        ),
    ]
